# Generated by Django 5.0.7 on 2024-07-24 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BlogApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postagem",
            options={"verbose_name_plural": "Postagens"},
        ),
    ]
